# Generated by Django 2.2.4 on 2019-08-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orm_article',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
